### ISSUE TITLE
Better docs please...

### ISSUE THREAD

**Issue by mgifford** [phase2/docker-pa11y#9]
This looks pretty straight forward, and I'd think I should be able to use:

<img width="558" alt="screen shot 2018-05-28 at 12 52 38 pm" src="https://user-images.githubusercontent.com/116832/40623676-0fadf382-6276-11e8-8245-301c9c84be31.png">

```
$ docker pull outrigger/pa11y
Using default tag: latest
Error response from daemon: manifest for outrigger/pa11y:latest not found
```

It almost works with:
```docker pull outrigger/pa11y:1```

but it gives me:

```
$ docker run outrigger/pa11y:1 https://amazon.com

Welcome to Pa11y

 > Running Pa11y on URL https://amazon.com

Error: Failed to launch chrome!
[0528/165137.890742:FATAL:zygote_host_impl_linux.cc(126)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x56549e7f82ec base::debug::StackTrace::StackTrace()
#1 0x56549e80f73c logging::LogMessage::~LogMessage()
#2 0x56549d8940d1 content::ZygoteHostImpl::Init()
#3 0x56549d50e045 content::BrowserMainLoop::EarlyInitialization()
#4 0x56549d514222 content::BrowserMainRunnerImpl::Initialize()
#5 0x5654a26e0059 headless::HeadlessContentMainDelegate::RunProcess()
#6 0x56549e534f60 content::RunNamedProcessTypeMain()
#7 0x56549e535975 content::ContentMainRunnerImpl::Run()
#8 0x56549e53ec5f service_manager::Main()
#9 0x56549e534481 content::ContentMain()
#10 0x5654a26df1fa headless::(anonymous namespace)::RunContentMain()
#11 0x5654a26df26e headless::HeadlessBrowserMain()
#12 0x56549e53ba6a headless::HeadlessShellMain()
#13 0x56549cdc11c5 ChromeMain
#14 0x7fb4500e3b45 __libc_start_main
#15 0x56549cdc102a _start

Received signal 6
#0 0x56549e7f82ec base::debug::StackTrace::StackTrace()
#1 0x56549e7f7e51 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7fb455f5e890 <unknown>
#3 0x7fb4500f7067 gsignal
#4 0x7fb4500f8448 abort
#5 0x56549e7f6aa5 base::debug::BreakDebugger()
#6 0x56549e80fb3f logging::LogMessage::~LogMessage()
#7 0x56549d8940d1 content::ZygoteHostImpl::Init()
#8 0x56549d50e045 content::BrowserMainLoop::EarlyInitialization()
#9 0x56549d514222 content::BrowserMainRunnerImpl::Initialize()
#10 0x5654a26e0059 headless::HeadlessContentMainDelegate::RunProcess()
#11 0x56549e534f60 content::RunNamedProcessTypeMain()
#12 0x56549e535975 content::ContentMainRunnerImpl::Run()
#13 0x56549e53ec5f service_manager::Main()
#14 0x56549e534481 content::ContentMain()
#15 0x5654a26df1fa headless::(anonymous namespace)::RunContentMain()
#16 0x5654a26df26e headless::HeadlessBrowserMain()
#17 0x56549e53ba6a headless::HeadlessShellMain()
#18 0x56549cdc11c5 ChromeMain
#19 0x7fb4500e3b45 __libc_start_main
#20 0x56549cdc102a _start
  r8: ffff99a4f6225ce0  r9: ffff99a4f6225cd0 r10: 0000000000000008 r11: 0000000000000206
 r12: 00007ffd56e63f98 r13: 00007ffd56e63f88 r14: 00007ffd56e63f90 r15: 00007ffd56e63b40
  di: 0000000000000011  si: 0000000000000011  bp: 00007ffd56e63ad0  bx: 00007ffd56e63b40
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007fb4500f7067  sp: 00007ffd56e63998
  ip: 00007fb4500f7067 efl: 0000000000000206 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/Launcher.js:226:14)
    at Interface.helper.addEventListener (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/Launcher.js:215:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:370:8)
    at Socket.onend (readline.js:149:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

**Comment by mgifford** [comment]
Maybe I just need to RTFM:

```
docker run -i --rm --cap-add=SYS_ADMIN \
  --name pa11y outrigger/pa11y:1 http://outrigger.sh
```
